In [2]:
import pandas as pd
import os

In [12]:
start_date = 20260724
end_date = 20260806

In [13]:
for date in range(start_date, end_date + 1) :
    print(date)

20260724
20260725
20260726
20260727
20260728
20260729
20260730
20260731
20260732
20260733
20260734
20260735
20260736
20260737
20260738
20260739
20260740
20260741
20260742
20260743
20260744
20260745
20260746
20260747
20260748
20260749
20260750
20260751
20260752
20260753
20260754
20260755
20260756
20260757
20260758
20260759
20260760
20260761
20260762
20260763
20260764
20260765
20260766
20260767
20260768
20260769
20260770
20260771
20260772
20260773
20260774
20260775
20260776
20260777
20260778
20260779
20260780
20260781
20260782
20260783
20260784
20260785
20260786
20260787
20260788
20260789
20260790
20260791
20260792
20260793
20260794
20260795
20260796
20260797
20260798
20260799
20260800
20260801
20260802
20260803
20260804
20260805
20260806

In [5]:
scrap_review_df = pd.read_csv('../data/raw/movie_review_scrap/movie_review_scrap_20260807.csv')
scrap_info_df = pd.read_csv('../data/raw/movie_info_scrap/movie_info_scrap_20260807.csv')
api_info_df = pd.read_csv('../data/raw/movie_info_api/movie_info_api_20260806.csv')

In [10]:
scrap_review_df.info()
scrap_review_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             45 non-null     int64
 1   reviewer_name  45 non-null     object
 2   score          45 non-null     int64
 3   review         45 non-null     object
 4   c_datetime     45 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.9+ KB

,id,reviewer_name,score,review,c_datetime
0,63091,송경원,7,하이틴의 겉옷을 벗고 근본으로 돌아간 성장,2026-08-07 14:32:30
1,63091,정재현,7,큰 힘과 큰 책임이 서로를 따르지 못할 때에도 당신이 히어로라면,2026-08-07 14:32:30
2,63091,이자연,7,도파민형 영웅이 가득한 세상에서 ‘선함’을 지켜낸 ‘강한’ 히어로,2026-08-07 14:32:30
3,63091,이우빈,7,역시 스파이더맨은 고통받을수록 강하고 재밌다,2026-08-07 14:32:30
4,63091,박평식,7,캐릭터도 캐스트도 발맞춰 잘 자랐구나,2026-08-07 14:32:30

In [7]:
scrap_info_df

,rank,title,score,daily_audience,total_audience,release_date,href,id,genre,grade,time,director,expert_score,nation,c_datetime
0,1,스파이더맨: 브랜드 뉴 데이,7.33,2988829,4646132,2026-07-29,/movie/info/?movie_id=63091,63091,"판타지,어드벤처,액션",12세이상관람가,144분,데스틴크리튼,7.33,미국,2026-08-07 14:32:30
1,2,오디세이,7.55,539180,539804,2026-08-05,/movie/info/?movie_id=62585,62585,"액션,모험,드라마",15세이상관람가,172분,크리스토퍼놀란,7.55,미국,2026-08-07 14:32:31
2,3,호프,6.83,436585,4292726,2026-07-15,/movie/info/?movie_id=62480,62480,"액션,스릴러,SF",15세이상관람가,156분,나홍진,6.83,한국,2026-08-07 14:32:32
3,4,사랑의 하츄핑: 고래보석의 전설,7.00,138674,144186,2026-08-05,/movie/info/?movie_id=63075,63075,애니메이션,전체관람가,105분,김수훈,7.00,한국,2026-08-07 14:32:34
4,5,미니언즈 & 몬스터즈,6.50,79932,748798,2026-07-15,/movie/info/?movie_id=63032,63032,애니메이션,전체관람가,89분,피에르코팽,6.50,미국,2026-08-07 14:32:35
5,6,모아나,5.67,43199,1017212,2026-07-08,/movie/info/?movie_id=62818,62818,"어드벤처,액션",전체관람가,115분,토마스케일,5.67,미국,2026-08-07 14:32:36
6,7,토이 스토리 5,6.83,42266,2932601,2026-06-17,/movie/info/?movie_id=62799,62799,애니메이션,전체관람가,101분,앤드류스탠튼,6.83,미국,2026-08-07 14:32:37
7,8,다윗,5.00,27880,272513,2026-07-10,/movie/info/?movie_id=63108,63108,애니메이션,전체관람가,109분,필커닝햄,5.00,미국,2026-08-07 14:32:38
8,9,어떻게 해야 했을까?,6.50,25333,37683,2026-07-29,/movie/info/?movie_id=63282,63282,다큐멘터리,12세이상관람가,101분,후지노토모아키,6.50,일본,2026-08-07 14:32:40
9,10,눈동자,5.00,8427,1540882,2026-06-24,/movie/info/?movie_id=63186,63186,스릴러,15세이상관람가,105분,염지호,5.00,한국,2026-08-07 14:32:41

In [8]:
api_info_df

,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,c_date
0,1,0,OLD,20250654,오디세이,2026-08-05,2670543690,45.2,-466050550,-14.9,5836528930,246075,-46635,-15.9,541152,1660,4912,2026-08-07 14:36:56
1,2,0,OLD,20262770,스파이더맨: 브랜드 뉴 데이,2026-07-29,2366180920,40.1,-359225810,-13.2,48713695820,237917,-37264,-13.5,4647267,1694,5675,2026-08-07 14:36:56
2,3,0,OLD,20262381,사랑의 하츄핑: 고래보석의 전설,2026-08-05,386108380,6.5,-273477100,-41.5,1363699980,43744,-29421,-40.2,144319,801,1698,2026-08-07 14:36:56
3,4,0,OLD,20233219,호프,2026-07-15,261790550,4.4,-29187620,-10.0,46031396410,27187,-2883,-9.6,4292963,688,1163,2026-08-07 14:36:56
4,5,0,OLD,20261784,미니언즈 & 몬스터즈,2026-07-15,38671200,0.7,-7351050,-16.0,7461916690,4644,-668,-12.6,748687,284,313,2026-08-07 14:36:56
5,6,0,NEW,20255484,오케이 마담2,2026-08-12,40293000,0.7,40293000,100.0,71506000,4477,4477,100.0,7884,25,25,2026-08-07 14:36:56
6,7,-1,OLD,20264148,어떻게 해야 했을까?,2026-07-29,33461550,0.6,-5563220,-14.3,377043650,3418,-714,-17.3,37696,78,143,2026-08-07 14:36:56
7,8,-1,OLD,20259781,토이 스토리 5,2026-06-17,24098200,0.4,-1890550,-7.3,30146288860,2662,-106,-3.8,2932984,148,154,2026-08-07 14:36:56
8,9,0,OLD,20262902,다윗,2026-07-10,14737500,0.2,2016900,15.9,2649418290,1607,217,15.6,272490,77,81,2026-08-07 14:36:56
9,10,-2,OLD,20259946,모아나,2026-07-08,13790550,0.2,-6168710,-30.9,10789245180,1534,-791,-34.0,1017656,106,113,2026-08-07 14:36:56